-- Active: 1749757574490@@127.0.0.1@5432@petagenda
-- Criando Tabela Cliente
CREATE TABLE cliente(

    idcliente SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL

);


-- Criando Tabela Admin 

CREATE TABLE admin(

    idadmin SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR (255) NOT NULL , 
    telefone VARCHAR(20) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

-- Criando tabelasolicitação agendamento
CREATE TABLE soliagenda(
    idsoli SERIAL PRIMARY KEY,
    idcliente INT NOT NULL,
    dtsoli DATE DEFAULT NOW(),
    idadmin INT,
    confirmsoli BOOLEAN,
    descricao VARCHAR(255),
    FOREIGN KEY (idadmin) REFERENCES admin(idadmin),
    FOREIGN KEY (idcliente) REFERENCES cliente(idcliente)
);

-- Criando tabela agenda
CREATE TABLE agenda(

    idagenda SERIAL PRIMARY KEY,
    idsoli INT,
    diasemana VARCHAR(15),
    dthagenda TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY(idsoli) REFERENCES soliagenda(idsoli)

);

/*

DROP TABLE cliente;
DROP TABLE admin;
DROP TABLE soliagenda;
DROP TABLE agenda;


-- FAZENDO DELETE BÁSICO

DELETE FROM cliente;

DELETE FROM admin;

DELETE FROM soliagenda;

DELETE FROM agenda;

*/